axon:
  axonserver:
    enabled: false
  serializer: 
    general: jackson
    events: jackson
    messages: jackson

  kafka:
    bootstrap-servers: localhost:29092,localhost:29094,localhost:29096
    default-topic: Axon.Account.Events
    client-id: kafka-axon-account
    message-converter-mode: default # alternative is cloud_event <https://cloudevents.io/>
    properties:
      security.protocol: PLAINTEXT # PLAINTEXT for no security purpose
    publisher:
      confirmation-mode: transactional
    producer:
      transaction-id-prefix: kafka-axon-account-txn
      retries: 5 # bigger than zero in case of using transactional confirmation-mode
      event-processor-mode: tracking
    consumer:
      event-processor-mode: pooled_streaming


server:
  port: 20261

spring:
  application:
    name: account

  profiles:
    active: dev
  config:
    import: optional:configserver:http://localhost:8888
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:9090

  datasource:
    url: jdbc:postgresql://localhost:16852/db_account
    username: itpusr
    password: itp@168
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        format_sql: true


# this alternative if eureka cannot resolve service's hostname for discovery concept
#eureka:
#  instance:
#    instance-id: ${spring.application.name}
#    prefer-ip-address: true
logging:
  level:
    org.springframework.security: DEBUG
    org.springframework.security.oauth2: DEBUG
    org.springframework.cloud.gateway: DEBUG